import { PageShell } from "@/components/layout/PageShell";
import { AUDIT_REPORTS } from "@/lib/mock-data";
import { StatusChip } from "@/components/ui/StatusChip";
import { Button } from "@/components/ui/Button";
import { Download, Plus, FileText, Clock } from "lucide-react";

const TEMPLATES = [
  { name: "HIPAA Readiness Report", desc: "PHI detection, masking coverage, and policy adherence", icon: "🏥" },
  { name: "GDPR Masking Audit", desc: "Personal data handling across all sessions", icon: "🇪🇺" },
  { name: "Voice Redaction Evidence", desc: "Per-session redaction proof for voice channels", icon: "🎙️" },
  { name: "Key Access & Rotation Summary", desc: "KEK usage, rotation history, and access logs", icon: "🔑" },
  { name: "Custom Report Builder", desc: "Define your own scope, filters, and evidence set", icon: "⚙️" },
];

export default function AuditReportsPage() {
  return (
    <PageShell title="Audit Reports">
      <div className="flex items-start justify-between mb-6">
        <div>
          <h2 className="text-[18px] font-semibold tracking-tight text-[#0d0f12]">Audit Reports</h2>
          <p className="text-[13px] text-[#6b7280] mt-1">Generate downloadable evidence by use case, framework, and date range.</p>
        </div>
        <Button variant="primary">
          <Plus className="w-3.5 h-3.5" /> Generate Report
        </Button>
      </div>

      {/* Templates */}
      <div className="mb-6">
        <div className="text-[12px] font-semibold text-[#9ca3af] uppercase tracking-wide mb-3">Report Templates</div>
        <div className="grid grid-cols-5 gap-3">
          {TEMPLATES.map((t) => (
            <button
              key={t.name}
              type="button"
              aria-label={`Generate ${t.name}`}
              className="flex flex-col gap-2 p-4 rounded-lg border border-[#e5e7eb] bg-white text-left hover:border-[#0d0f12] hover:shadow-sm transition-all group focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#0d0f12]"
            >
              <span className="text-xl">{t.icon}</span>
              <div className="text-[12px] font-semibold text-[#0d0f12] group-hover:text-[#0d0f12] leading-snug">{t.name}</div>
              <div className="text-[11px] text-[#9ca3af] leading-snug">{t.desc}</div>
            </button>
          ))}
        </div>
      </div>

      {/* Generated reports */}
      <div className="rounded-lg border border-[#e5e7eb] bg-white overflow-hidden">
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-[#e5e7eb]">
          <div className="text-[13px] font-semibold text-[#0d0f12]">Generated Reports</div>
          <div className="flex items-center gap-2 text-[12px] text-[#9ca3af]">
            <Clock className="w-3.5 h-3.5" aria-hidden="true" />
            {AUDIT_REPORTS.filter((r) => r.status === "scheduled").length} scheduled
          </div>
        </div>
        <table className="w-full text-[12px]">
          <thead className="bg-[#fafafa]">
            <tr className="text-[#9ca3af] border-b border-[#e5e7eb]">
              <th className="text-left px-5 py-3 font-medium">Report</th>
              <th className="text-left px-5 py-3 font-medium">Use Case</th>
              <th className="text-left px-5 py-3 font-medium">Date Range</th>
              <th className="text-left px-5 py-3 font-medium">Sessions</th>
              <th className="text-left px-5 py-3 font-medium">Generated By</th>
              <th className="text-left px-5 py-3 font-medium">Status</th>
              <th className="text-left px-5 py-3 font-medium">Download</th>
            </tr>
          </thead>
          <tbody>
            {AUDIT_REPORTS.map((r) => (
              <tr key={r.id} className="border-b border-[#f9fafb] last:border-0 hover:bg-[#fafafa] transition-colors">
                <td className="px-5 py-3.5">
                  <div className="flex items-center gap-2">
                    <FileText className="w-3.5 h-3.5 text-[#9ca3af] shrink-0" />
                    <span className="font-medium text-[#0d0f12]">{r.name}</span>
                  </div>
                </td>
                <td className="px-5 py-3.5 text-[#6b7280]">{r.useCase}</td>
                <td className="px-5 py-3.5 text-[#6b7280]">{r.dateRange}</td>
                <td className="px-5 py-3.5 text-[#374151]">{r.sessionCount > 0 ? r.sessionCount.toLocaleString() : "—"}</td>
                <td className="px-5 py-3.5 font-mono text-[#9ca3af]">{r.generatedBy}</td>
                <td className="px-5 py-3.5"><StatusChip status={r.status} /></td>
                <td className="px-5 py-3.5">
                  {r.status === "ready" ? (
                    <div className="flex items-center gap-1.5">
                      {r.formats.map((f) => (
                        <button
                          key={f}
                          className="flex items-center gap-1 px-2 py-1 rounded border border-[#e5e7eb] text-[11px] font-medium text-[#6b7280] hover:border-[#0d0f12] hover:text-[#0d0f12] transition-colors"
                        >
                          <Download className="w-3 h-3" /> {f}
                        </button>
                      ))}
                    </div>
                  ) : (
                    <span className="text-[#9ca3af]">—</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </PageShell>
  );
}
